### ISSUE TITLE
Cars that haven't been adapted yet can still have turn signals, taillights, etc. activated, even with the GlobalIndicators option disabled.

### ISSUE THREAD

**Issue by Crowdigger** [user-grinch/ModelExtras#12]
https://github.com/user-grinch/ModelExtras/assets/98184183/6e0ee78c-e1a3-4d4d-b96f-e10c12abc6f8

**Comment by user-grinch** [comment]
Do these vehicles have `turnl_` or `indicator_` dummies in them? If so send me the models.

**Comment by Crowdigger** [comment]
No, they are vanilla cars

**Comment by user-grinch** [comment]
GlobalIndicators only disables turn signals for non-adapted vehicles. I did some fixes, it should resolve in the next build. Let me know the update/s.
