### ISSUE TITLE
Incompatibility with PedFuncs

### ISSUE THREAD

**Issue by VadimZhukovskiy1997** [user-grinch/ModelExtras#18]
Version: April 17

Other relevant mods used:
[PedFuncs](https://www.mixmods.com.br/2022/07/pedfuncs/)
[Original Peds Vary](https://www.mixmods.com.br/2021/03/original-peds-vary-peds-originais-variando-pedfuncs/)

By activating ModelExtras, it makes some peds have white (no) textures

![image](https://github.com/user-grinch/ModelExtras/assets/47507382/451247b8-084e-460f-a74d-c56df03568c3)

**Comment by user-grinch** [comment]
ModelExtras has the same functionality of PedFuncs. You can safely remove PedFuncs and mods made for PedFuncs should work fine.

**Comment by VadimZhukovskiy1997** [comment]
This happened after I removed PedFuncs.
![image](https://github.com/user-grinch/ModelExtras/assets/47507382/60207c72-af06-45c9-877d-860d1b40a47d)

**Comment by VadimZhukovskiy1997** [comment]
So far what I have discovered is any ped texture has more than 2 remaps will have the no texture issue:
![image](https://github.com/user-grinch/ModelExtras/assets/47507382/b03f695b-e836-4256-b182-b23fb66812ee)
![image](https://github.com/user-grinch/ModelExtras/assets/47507382/6d1ad027-5c40-45fa-b211-fce635c1afa3)

And this one is normal:
![image](https://github.com/user-grinch/ModelExtras/assets/47507382/39fe385d-951a-4fe9-9c9e-8c31e43c7b6d)

**Comment by user-grinch** [comment]
I checked and seems to work fine. Can you provide steps to reproduce?
