### ISSUE TITLE
Siren materials (x-255-255) do not work

### ISSUE THREAD

**Issue by KaiQ-1** [user-grinch/ModelExtras#22]
The siren materials keep the material color instead of turning them white, with the exception of the first one (1-255-255). All of them, without exception, also do not light up, even if the texture is named "siren" at the beginning. The siren works fine in AVS build 4.
Images with ModelExtras:
![Sem título](https://github.com/user-attachments/assets/f200afe0-f43d-4245-b30c-99bca5055618)
![Sem título2](https://github.com/user-attachments/assets/96e4f71a-0fae-4a29-8444-a61b9e41d171)

Images with AVS build 4 (the last):
![Sem títul4](https://github.com/user-attachments/assets/f4046fe1-00f1-4e14-8a88-c1c0feb025ed)
![Sem títul3o](https://github.com/user-attachments/assets/5b362def-7954-4e5e-9df2-5df76cc3f8ef)

**Comment by user-grinch** [comment]
It should be resolved. Check discord
