### ISSUE TITLE
disable vehicle coronas (and shadow) on impact

### ISSUE THREAD

**Issue by KaiQ-1** [user-grinch/ModelExtras#24]
basically: make the corona (and shadow) dummies disappear when a part detaches from the car so that this doesn't happen:

![Sem título](https://github.com/user-attachments/assets/0f81cfe9-bc56-4f7b-83a9-8f746b407190)

-The way I thought of is to make the dummy take into account its hierarchy. 
If it is a child of a part and it is being rendered by the game, the corona dummy will work. This would also make it possible to add a dummy with a certain position as a child of a _ok part and another dummy with the same name with a different position in a _dam part. When the game replaces the _ok part with the _dam part, the _ok corona light will stop working and the _dam corona light will take its place. When the _dam part is detached from the vehicle, neither will work.
Example:
├ chassis_dummy
.......├ bump_rear_dummy
...............├ bump_rear_ok
........................├ indicator_lr 
........................├ indicator_rr
...............├ bump_rear_dam
........................├ indicator_lr
........................├ indicator_rr
.......├ chassis
...............├ indicator_lm
...............├ indicator_rm
 
-Or another alternative would be to identify how the headlights originally work in the game. 
I believe they detect any collision close to the dummy. If there is, disable the corona, shadow and texture ON corresponding to the material color of the dummy. This would also be a good idea

**Comment by user-grinch** [comment]
This can be implemented, but not for existing models. Future models will need to be adjusted slightly.

**Comment by user-grinch** [comment]
Implemented
