### ISSUE TITLE
Reverse Light

### ISSUE THREAD

**Issue by CanerKaraca23** [user-grinch/ModelExtras#26]
https://discord.com/channels/689515979847237649/1129105388168556554/1286639577867751445

Reverse light corona and shadow too bright.

Also, can you make the light shadow ImVehFt like?

**Comment by user-grinch** [comment]
I've fixed the brightness issue. What do you mean like ImVehFt like?

**Comment by CanerKaraca23** [comment]
> I've fixed the brightness issue. What do you mean like ImVehFt like? Open a new issue for it

You made taillights ImVehFt like before, make reverse light too. @user-grinch
