### ISSUE TITLE
ImVehFt Long Shadows

### ISSUE THREAD

**Issue by CanerKaraca23** [user-grinch/ModelExtras#35]
Add long shadows with G button like on ImVehFt. Not fog lights J button.

![sa-mp-005](https://github.com/user-attachments/assets/7ab1d61a-801b-4599-af27-45c2c8e161e6)

![sa-mp-006](https://github.com/user-attachments/assets/c8ba780f-f971-4896-9c2a-c0c2e44c2172)

![sa-mp-007](https://github.com/user-attachments/assets/ab1516dd-f17e-4d81-bec1-4f197af75743)

![sa-mp-008](https://github.com/user-attachments/assets/0ed7a8e2-b895-4472-9158-991cb025ec44)

**Comment by user-grinch** [comment]
Added

**Comment by CanerKaraca23** [comment]
> Added

Can you also add the brightness change of corona when you enable long shadows like on the last 2 screenshots that i added on first message like on ImVehFt?

Also can you add toggle 'click' sound effect when you press G button like on ImVehFt? @user-grinch
