### ISSUE TITLE
Reverse Light Again...

### ISSUE THREAD

**Issue by CanerKaraca23** [user-grinch/ModelExtras#36]
https://github.com/user-grinch/ModelExtras/issues/26

Continuation of this issue, another second car bug...
Reverse light shadow and corona too bright when you got second car. On first, it fixed, thanks.

![sa-mp-009](https://github.com/user-attachments/assets/f308a434-a121-4b33-907f-0cb9b3048ee0)

**Comment by user-grinch** [comment]
Fixed
