### ISSUE TITLE
Brake Light Shadow Issue

### ISSUE THREAD

**Issue by CanerKaraca23** [user-grinch/ModelExtras#38]
The taillight shadow is no longer getting more intense when the brake is activated. This also affects vanilla vehicles without adaptation.

Reported by @KaiQ-1 confirmed by me.

![sa-mp-002](https://github.com/user-attachments/assets/05396cbd-74a0-4a98-bec9-d91005f75d18)
![sa-mp-003](https://github.com/user-attachments/assets/ea9e0d6f-0b72-458c-a75a-f82f5b9c7fe2)

**Comment by user-grinch** [comment]
Fixed
