### ISSUE TITLE
Vehicle Sirens Problems

### ISSUE THREAD

**Issue by CanerKaraca23** [user-grinch/ModelExtras#41]
- Vehicle sirens textures are not changing when sirens are activating.
- There is 2 coronas on siren place, where it shouldn't.
- Vehicle sirens coronas are appears at angles where they shouldn't be visible.

https://github.com/user-attachments/assets/575388a9-6b2e-4349-8507-7d1473a3c08c

https://github.com/user-attachments/assets/c4041d5e-742e-47ab-90bf-cf96b008e51e

https://github.com/user-attachments/assets/3dd30bcb-3d8e-4fc4-896a-3a74c19a132c

**Comment by user-grinch** [comment]
Tracking this here https://github.com/user-grinch/ModelExtras/issues/47
