### ISSUE TITLE
Vehicle Headlight Becomes Crazy When You Hit Somewhere

### ISSUE THREAD

**Issue by CanerKaraca23** [user-grinch/ModelExtras#42]
Vehicles with opened sirens headlight becomes crazy when you hit somewhere.

https://github.com/user-attachments/assets/cffcd080-de3d-4bef-8c9a-11b9e2bcb1f0

**Comment by user-grinch** [comment]
Tracking this https://github.com/user-grinch/ModelExtras/issues/47
