### ISSUE TITLE
Weird Light Shadow Under Car

### ISSUE THREAD

**Issue by CanerKaraca23** [user-grinch/ModelExtras#43]
This is a rare issue (Maybe another second car bug?).
It exists even reverse lights shadows are enabled, so i guess it's not related to reverse light shadows.

![sa-mp-001](https://github.com/user-attachments/assets/d8c5bafe-7d31-4157-9862-d580de6ec7ac)

**Comment by user-grinch** [comment]
Does it happen for any model or a few specific ones?

**Comment by CanerKaraca23** [comment]
> Does it happen for any model or a few specific ones?

I think public services cars like police cars. Not sure.

**Comment by user-grinch** [comment]
Tried police and ambulance. Didn't appear for me. Send me the model next time you face it.

**Comment by CanerKaraca23** [comment]
> Tried police and ambulance. Didn't appear for me. Send me the model next time you face it.

Maybe i guess it's the shadow of the coronas on siren's place. I reported this corona on another issue. Will try and test further and will send the models i use. All my cars from RVP btw. @user-grinch

**Comment by CanerKaraca23** [comment]
[copcarsf.zip](https://github.com/user-attachments/files/18229840/copcarsf.zip)

Here the vehicle, i tested and encountered again. Try as a second car. @user-grinch
