### ISSUE TITLE
Motorcycles Bugs On ModelExtras

### ISSUE THREAD

**Issue by CanerKaraca23** [user-grinch/ModelExtras#45]
Motorcycle on video is ImVehFt supported.

- Indicator lights shadows positions are wrong.
- Indicator lights and headlight textures are not changing while open/off.
- Some motorcycles don't have indicator lights shadows.
- Headlight corona position is a bit wrong.

Vehicle used on video (DFF only):
[fcr900.zip](https://github.com/user-attachments/files/18220060/fcr900.zip)

![sa-mp-004](https://github.com/user-attachments/assets/4c2917cf-6697-4dab-bb8b-60e1bfd0fdea)

https://github.com/user-attachments/assets/f7f48d7f-950d-4da2-8ade-d6677d53d63b

**Comment by user-grinch** [comment]
The FCR bike isn't adapted to indcator lights. It has no dummeis.

**Comment by CanerKaraca23** [comment]
> The FCR bike isn't adapted to indcator lights. It has no dummeis.

Works properly on ImVehFt. @user-grinch 

https://github.com/user-attachments/assets/99b955df-12c9-4e21-a5e7-d883f80ea5ce

**Comment by user-grinch** [comment]
> > The FCR bike isn't adapted to indcator lights. It has no dummeis.
> 
> Works properly on ImVehFt. @user-grinch
> 
>  2024-12-23.16-52-10.mp4

It doesn't there are no corona on the bike. What you're seeing is just the materials lighting up.

**Comment by CanerKaraca23** [comment]
> > > The FCR bike isn't adapted to indcator lights. It has no dummeis.
> > 
> > 
> > Works properly on ImVehFt. @user-grinch
> > 2024-12-23.16-52-10.mp4
> 
> It doesn't there are no corona on the bike. What you're seeing is just the materials lighting up (Which isn't working in ModelExtras atm)
> 
> The wrong placed coronas you're seeing is part of the GlobalIndicaors feature which is expected.

Oh, didn't know about that. Ok then, removed the corona from list. @user-grinch

**Comment by user-grinch** [comment]
This https://github.com/user-grinch/ModelExtras/commit/049c73a90f94865ea587b7ffadd4e27d58a5d642 should resolve issues with headlights & turnlights

**Comment by CanerKaraca23** [comment]
> This [049c73a](https://github.com/user-grinch/ModelExtras/commit/049c73a90f94865ea587b7ffadd4e27d58a5d642) should resolve issues with headlights & turnlights

- Headlight texture is still not changing.
- I just realized that FCR-900 don't have indicator light shadows.
@user-grinch 

![sa-mp-000](https://github.com/user-attachments/assets/c1eda477-9140-431f-9ffc-469a29ad256b)
![sa-mp-001](https://github.com/user-attachments/assets/c4e09013-deaa-487a-955c-58c0dc38f840)

**Comment by user-grinch** [comment]
This model half implements the feature. Both corona and shadows are dependent on dummies but it doesn't have it. So these issues are expected.

I'll take a look at why GlobalIndicators shadows aren't appearing but don't expect them to line up with their materials.

**Comment by user-grinch** [comment]
> This model half implements the feature. Both corona and shadows are dependent on dummies but it doesn't have it. So these issues are expected.
> 
> I'll take a look at why GlobalIndicators shadows aren't appearing but don't expect them to line up with their materials.

I've rechecked the code. It seems to be working as expected. Without dummies inside the model, I don't think there's a way to add shadows atm.

**Comment by CanerKaraca23** [comment]
Ok then, you can close if you want @user-grinch

**Comment by CanerKaraca23** [comment]
@user-grinch forgot the "Indicator lights shadows positions are wrong." thing, you can reopen if you want.
