### ISSUE TITLE
Crash when configuring Fastman Limited 

### ISSUE THREAD

**Issue by ValentinoProM123** [user-grinch/ModelExtras#9]
When using Fastman normally, the mod works fine but when configuring a value, more precisely the line called FILE_TYPE_DFF within the txt, the game crashes indefinitely either when turning on the turn signals, the fog lights or the siren. police the game closes, this line in fastman allows increasing the ID limit of dff objects, used to create new maps, I don't know if there is a solution, the problem also happens in other similar mods (Imvehft or AVS)

**Comment by user-grinch** [comment]
Send me your fla ini file

**Comment by user-grinch** [comment]
Closing this, since no response.
